# Generated by Django 6.0.5 on 2026-05-31 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculator',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload custom icon image (PNG, SVG, WebP). Overrides emoji icon.', null=True, upload_to='icons/calculators/'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload custom icon image (PNG, SVG, WebP). Overrides emoji icon.', null=True, upload_to='icons/categories/'),
        ),
    ]
