# Generated by Django 6.0.5 on 2026-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculators', '0002_calculator_icon_image_category_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='og_image',
            field=models.ImageField(blank=True, help_text='1200 x 630 pixels (landscape)', null=True, upload_to='seo/'),
        ),
    ]
